/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type EmploymentContractType = "b2b" | "internship" | "mandate contract" | "permanent" | "specific-task contract";

export type Experience = "junior" | "manager / c-level" | "mid" | "not applicable" | "senior";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type PaymentBasis = "gross" | "net";

export type SalaryType = "annual" | "daily" | "hourly" | "monthly";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type WorkingMode = "hybrid" | "office";

export type WorkType = "freelance" | "full-time" | "part-time" | "practice / internship";

export interface Company {
  description: string | null;
  id: Generated<number>;
  image: string | null;
  industry: string | null;
  name: string;
  website: string | null;
}

export interface JobLocations {
  address_line1: string;
  address_line2: string | null;
  city: string;
  country: string;
  id: number;
  job_posting_id: string;
  working_mode: WorkingMode;
  zip_code: string;
}

export interface JobPostings {
  company_id: number;
  description: string;
  employment_contract_type: EmploymentContractType;
  experience: Experience;
  expires_at: Timestamp;
  id: string;
  is_remote_available: boolean;
  name: string;
  payment_basis: PaymentBasis | null;
  published_at: Timestamp;
  salary_max: Numeric | null;
  salary_min: Numeric | null;
  salary_type: SalaryType | null;
  work_type: WorkType;
}

export interface Office {
  address: string | null;
  company_id: number;
  id: Generated<number>;
}

export interface DB {
  company: Company;
  job_locations: JobLocations;
  job_postings: JobPostings;
  office: Office;
}
